### ISSUE TITLE
Padding zwischen Artikelname & Artikelbild etwas vergrößern

### ISSUE THREAD

**Issue by MauveSchaeder** [CaesarGustav/WacgAngularSearch#3]
Aktuell sitzt der Artikelname sehr nah an dem Artikelbild. 
Hier sollte ein minimales Padding eingefügt werden.

**Comment by psren** [comment]
Meint ihr das mit den Bilchen links, oder im Popup, oder beides?

**Comment by MauveSchaeder** [comment]
![2015-01-15 09_06_26-startseite - apotheken demo-webshop](https://cloud.githubusercontent.com/assets/10531007/5754228/ea78967a-9c95-11e4-8b68-9c0fa026a3c4.png)
