### ISSUE TITLE
Mobile Darstellung

### ISSUE THREAD

**Issue by MauveSchaeder** [CaesarGustav/WacgAngularSearch#6]
Die mobile Darstellung müsste noch optimiert werden.
U.a. ist die Positionierung nicht korrekt (s. Screenshot)
![foto](https://cloud.githubusercontent.com/assets/10531007/5956263/841a6918-a7ac-11e4-9cb3-1b39ed741599.PNG)

**Comment by psren** [comment]
:-)

Für später habe ich da eine ganz andere Vision wie das auf Mobil funktionieren soll.
Fürs erste positioniere ich es einfach richtig.
